### ISSUE TITLE
Data is not available

### ISSUE THREAD

**Issue by shobhitt10** [ravikiranrao/PD-EEG#1]
Hi, I found your work very interesting and wanted to reproduce/ extend it.
But, I could not find the dataset for classification.
Can you please upload it.
Thanks

**Comment by ravikiranrao** [comment]
Hi @shobhitt10, I'm glad for your interest in our work. Unfortunately, I do not have the rights to distribute the data. If you have already read the paper (https://arxiv.org/abs/2202.12936) regarding this repo, you will find more information about the data collection protocols and the original license holders. I suggest you to contact the authors of the dataset (given in our paper) to easily get the access :-)

**Comment by ravikiranrao** [comment]
Hi @shobhitt10, I'm glad for your interest in our work. Unfortunately, I do not have the rights to distribute the data. If you have already read the paper (https://arxiv.org/abs/2202.12936) regarding this repo, you will find more information about the data collection protocols and the original license holders. I suggest you to contact the authors of the dataset (given in our paper) to easily get the access :-)
